### ISSUE TITLE
External redis/credentials setup got broken in 2.10.2

### ISSUE THREAD

**Issue by gothrek22** [1Password/op-scim-helm#126]
### Your environment

Chart Version: any higher than 2.10.2

Helm Version: doesn't matter

Kubernetes Version: doesn't matter

## What happened?

So as part of the last two "minor" releases (please keep in mind that changing default behavior is by no means minor), the following things have been broken:
- using credentials secret together with custom redisUrl
- having separate settings for scimsession, workspaceSettingsFile, workspaceCredentialsFile 

## What did you expect to happen?

- better documentation (including examples of files that you want to be created/mounted like the workspace settings/credentials and scimsession file), 
- default behavior not changing between minor versions of the chart,
- 

## Steps to reproduce

Use the following yaml together with version 2.10.1 vs anything higher:
```yaml
scim:
  name: op-scim
  credentials: 
    volume:
      enabled: false
    secrets:
      enabled: true
      create: false
      scimsession:
        name: 1p-secret
        key: scimsession
          
  imagePullPolicy: Always

  service:
    enabled: true
    type: ClusterIP

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: domain
        paths:
          - path: /
            pathType: ImplementationSpecific

  config:
    jsonLogs: true
    redisUrl: redis://PROPER_REDIS_URL
  tls:
    enabled: false

  resources:
    requests:
      cpu: 125m
      memory: 256M
    limits:
      cpu: 250m
      memory: 512M

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80

  podDisruptionBudget:
    enabled: false
    minAvailable: 1

  serviceAccount:
    create: true

redis:
  enabled: false
```
