### ISSUE TITLE
Use Upstream Redis Dependency

### ISSUE THREAD

**Issue by thatguygriff** [1Password/op-scim-helm#20]
Currently the chart uses a custom Redis definition with minimal configuration for options like clustering and pod disruption budgets. We should move to using a maintained Redis chart with defaults that are similar to our current usage.

Adding a dependency to `op-scim-bridge/templates/op-scim.yaml` will allow for users to refer to that charts documentation on how to configure Redis beyond our default values.

```yaml
dependencies:
   - name: redis
     version: 12.0.0
     repository: https://charts.bitnami.com/bitnami
     condition: redis.enabled
```

Using this configuration would result in a similar configuration to the current default

```yaml
# -- Redis configuration, check [the upstream configuration](https://github.com/bitnami/charts/blob/master/bitnami/redis)
 redis:
   enabled: true
   image:
     registry: docker.io
     repository: bitnami/redis
     tag: 6.0.9-debian-10-r13
     pullPolicy: IfNotPresent
   cluster:
     enabled: false
   usePassword: false
```
