### ISSUE TITLE
Update chart name to op-scim-bridge

### ISSUE THREAD

**Issue by devillexio** [1Password/op-scim-helm#79]
Currently the `name` field in the `Chart.yaml` is set to "op-scim". This does not match what the chart should be called, which is "op-scim-bridge".

Further to that we also have several instances in the values and templates where we append "-bridge" to the chart name, for example (from `values.yaml`):
```yaml
scim:
  # name sets the name used for the various constructs used by the SCIM bridge setup
  name: "{{ .Chart.Name }}-bridge"
```

We should fix this inconsistency and set the chart name correctly. We should also ensure that the downstream apps that depend on this chart are updated.
