### ISSUE TITLE
Manage Secret externally

### ISSUE THREAD

**Issue by pniederlag** [1Password/op-scim-helm#87]
We would like to manage our secret for scimsession via external tooling (terraform). So we need to inject the proper secret into the pod/deployment but we do not want the chart to manage the secret as we then would have to store the credential either in the value files or the helm arguments when calling.

However there is currently one single setting that manages *both* parts:
* create/manage the Secret object
* inject the secret into the Pod/Deployment

```
scim:
  credentialsSecrets:
    scimsession:
      key: scimsession

```

**Comment by pniederlag** [comment]
@devillexio this is a real showstopper for us in using this chart. ;( would you consider any PR on this?

I have thought of 'scim.credentiasSecrets.manageSecret: true|false'

**Comment by devillexio** [comment]
Thanks for the additional context @pniederla. We have plans to make the enabling of the credentials volume/secret more explicit. Unfortunately I cannot commit any timelines. I'm hopeful that we can take a look once we have published the latest version of the SCIM bridge on all available channels.

**Comment by JonGilmore** [comment]
Agreed with @pniederlag - this seems weirdly inflexible for a company who's sole existence is credentials. I'd love to hear more about what is planned for improvements.

**Comment by todie** [comment]
> @devillexio this is a real showstopper for us in using this chart. ;( would you consider any PR on this?
> 
> I have thought of 'scim.credentiasSecrets.manageSecret: true|false'

I'm currently working on a fork of the chart to allow for external secrets and this change is unfortunately not trivial because of the assumptions made in multiple templates. Will try to PR upstream when it's ready.

**Comment by mruediger** [comment]
As a workaround we configured the secrets with empty values and used kustomize to remove the generated Secret object and defined it ourselves. Maybe that would work for you as well.

`values.yml`
```yaml
credentialsVolume: ""
credentialsSecrets:
  scimsession:
    key: scimsession
    value_json: "{}"
  workspaceCredentials:
    key: workspace-credentials
    value_json: "{}"
  workspaceSettings:
    key: workspace-settings
    value_json: "{}"
```

`kustomization.yaml`
```yaml
patchesStrategicMerge:
  - delete-secret.yaml
```

`delete-secret.yaml`
```yaml
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: foo-scim-bridge-credentials
  namespace: bar
```
