### ISSUE TITLE
Support redis name override for RedisURL

### ISSUE THREAD

**Issue by devillexio** [1Password/op-scim-helm#90]
Currently we use the default value for the `RedisURL` set to:
```yaml
  config:
    # redisURL sets the Redis connection URL
    redisURL: "redis://{{ .Release.Name }}-redis-master:6379"
```

This works until you specify the `nameOverride` or `fullnameOverride` for redis.

See the [common.names.fullname](https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_names.tpl#L21) template from `bitnami/common`.
